Agri_Energy_Connect_PROG7311_POE/Controllers/FarmersController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgriEnergyConnectApp.Models;
using System.Security.Cryptography; // For hashing passwords
using Microsoft.AspNetCore.Http; // For session management
using System.Text; // For encoding passwords

namespace AgriEnergyConnectApp.Controllers
{
    public class FarmersController : Controller
    {
        private readonly AgriEnergyConnectContext _context;
        AgriEnergyConnectContext db = new AgriEnergyConnectContext();

        public FarmersController(AgriEnergyConnectContext context)
        {
            _context = context;
        }

        // GET: Farmers
        // Retrieves all farmers from the database and renders them on the Index view
        public async Task<IActionResult> Index()
        {
            return View(await _context.Farmers.ToListAsync());
        }
        // GET: Products
        // Retrieves products for a specific farmer based on filtering criteria and renders them on the Products view
        public async Task<IActionResult> Products(string id,DateTime toDate,DateTime fromDate,string searchString)
        {
            // Passes data to the view for filtering and display
            ViewData["Farmer_ID"] = id;
            ViewData["toDate"] = toDate;
            ViewData["fromDate"] = fromDate;
            Helper.frmID = id;

            // Filters products based on search string if provided

            if (!String.IsNullOrEmpty(searchString))
            {   // Code to create filter function adapted from:
                //Author:Rick Anderson
                //Link:https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0
                // Filters database for searched product type
                var types = _context.Products.Where(p => p.Farmer_ID == id && p.Product_Type!.Contains(searchString));
                return View(await types.ToListAsync());
            }

            // Filters products based on date range if provided

            else if (toDate != default(DateTime) && fromDate != default(DateTime))
            {
                
              //Filters database to show products between 2 dates
                var type = _context.Products.Where(p => p.Farmer_ID == id && p.Product_Date >= fromDate && p.Product_Date <= toDate);
                return View(await type.ToListAsync());
            }
            else {

                // Displays all products for the specified farmer
                var AgriEnergyConnectContext = _context.Products.Where(p => p.Farmer_ID == id);
            return View(await AgriEnergyConnectContext.ToListAsync());

        }
        }

        // GET: Farmers/Create
        // Shows the form for creating a new farmer profile
        public IActionResult Create()
        {
            
            return View();
        }

        // POST: Products/Create
        // Handles form submission for creating a new farmer profile

        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Product_ID,Product_Name,Product_Price,Product_Quantity,Product_Type,Product_Date,Farmer_ID")] Product product)
        {
            if (ModelState.IsValid)
            // Retrieves current user's ID from session for association with the product
            {
                product.Farmer_ID = HttpContext.Session.GetString("CurrentUser");
                _context.Add(@product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["Farmer_ID"] = new SelectList(_context.Farmers, "Farmer_ID", "Farmer_ID", product.Farmer_ID);
            return View(product);
        }

         // GET: Farmers/Edit/5
        // Shows the form for editing a product
        
        public async Task<IActionResult> Edit(int? id)
        {

            ViewData["Farmer_ID"] = id;
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            // ViewData["Farmer_ID"] = new SelectList(_context.Farmers, "Farmer_ID", "Farmer_ID", product.Farmer_ID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Product_ID,Product_Name,Product_Price,Product_Quantity,Product_Type,Product_Date,Farmer_ID")] Product product,String frm)
        {
            frm = Helper.frmID;
            if (id != product.Product_ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    product.Farmer_ID = frm;
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Product_ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
            //ViewData["Farmer_ID"] = new SelectList(_context.Farmers, "Farmer_ID", "Farmer_ID", product.Farmer_ID);
            return View(product);
        }
        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Product_ID == id);
        }

        //Shows the Login form
        [HttpGet]
        public ActionResult Login()
        {
            return View();
        }


        //Recieves data from the login form
        [HttpPost]
        public ActionResult Login(Farmer f)
        {
            //Code below to hash Password 
            //Learnt and adapted from :
            //Author : Afzaal Ahmad Zeeshan
            //Link : https://www.c-sharpcorner.com/article/hashing-Passwords-in-net-core-with-tips/
            using (var sha256 = SHA256.Create())
            {

                HttpContext.Session.SetString("CurrentUser", f.Farmer_ID);
                //Variables declared to take in farmer ID and Password from login 
                string Farmer_ID = HttpContext.Session.GetString("CurrentUser");
                string pass = f.Password;


                // Hashes the password using SHA256
                var hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(pass));
                // Get hashed 
                var hash = BitConverter.ToString(hashedBytes).Replace("-", "").ToLower();

                // Matches farmer credentials with records in the database for authentication
                Farmer user = db.Farmers.Where(us => us.Farmer_ID.Equals(f.Farmer_ID) && us.Password.Equals(hash)).FirstOrDefault();

                if (user != null)
                {
                    //The user can now enter and will be taken to the main menu page
                    return RedirectToAction("New", "Home");
                }
                else
                {

                    // Displays error message for invalid credentials
                    ViewBag.Login = "INVALID USERNAME OR Password";
                    return View();

                }
            }


        }


        //Shows the form
        [HttpGet]
        public ActionResult Register()
        {
            return View();
        }

        //recieves data
        [HttpPost]
        public ActionResult Register(Farmer f)
        {
            HttpContext.Session.SetString("CurrentUser", f.Farmer_ID);
            string Farmer_ID = HttpContext.Session.GetString("CurrentUser");
            string pass = f.Password;
            string fname = f.FarmerName;
            using (var sha256 = SHA256.Create())
            {
                // Hashes the password using SHA256
                var hashedBytes = sha256.ComputeHash(Encoding.UTF8.GetBytes(pass));
                // Get the hashed string version of the Password
                var hash = BitConverter.ToString(hashedBytes).Replace("-", "").ToLower();

                // Creates a new farmer object to be stored in the database
                Farmer newF = new Farmer();
                newF.Farmer_ID = Farmer_ID;
                newF.Password = hash;
                newF.FarmerName = fname;
                // Checks if the user already exists in the database
                var UserAlreadyExists = db.Farmers.Any(x => x.Farmer_ID == newF.Farmer_ID);
                if (UserAlreadyExists)
                {

                    ViewBag.Fail = "USER WITH THIS ID NUMBER ALREADY EXISTS";
                }
                else
                {
                    // Adds the new farmer to the database
                    db.Farmers.Add(newF);
                    // Saves changes to the database using asynchronous method
                    db.SaveChangesAsync();

                    return RedirectToAction("Emp", "Home");
                }
            }
            return View();
        }

        // GET: Farmers1/Edit/5
        public async Task<IActionResult> Reset(string id)
        {
            id = HttpContext.Session.GetString("CurrentUser");
            if (id == null)
            {
                return NotFound();
            }

            var farmer = await _context.Farmers.FindAsync(id);
            if (farmer == null)
            {

Agri_Energy_Connect_PROG7311_POE/Controllers/ProductsController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.Rendering;
using Microsoft.EntityFrameworkCore;
using AgriEnergyConnectApp.Models;
using Microsoft.AspNetCore.Http;

namespace AgriEnergyConnectApp.Controllers
{
    public class ProductsController : Controller
    {
        private readonly AgriEnergyConnectContext _context;
       
        public ProductsController(AgriEnergyConnectContext context)
        {
            _context = context; // Initializing the database context
        }

        // GET: Products        
        // Action method to display products based on various filters

        public async Task<IActionResult> Index(String FarmerLogin, String searchString, DateTime toDate, DateTime fromDate)
        {
            FarmerLogin = HttpContext.Session.GetString("CurrentUser");
            // Setting view data for date filters

            ViewData["toDate"] = toDate;
            ViewData["fromDate"] = fromDate;


            // Handling different search criteria to filter products

            if (!String.IsNullOrEmpty(searchString))
                {
                // Code to create filter function adapted from:
                //Author:Rick Anderson
                //Link:https://docs.microsoft.com/en-us/aspnet/core/tutorials/first-mvc-app/search?view=aspnetcore-6.0
                // Filters database for searched product type
                var types = _context.Products.Where(x => x.Farmer_ID == FarmerLogin && x.Product_Type!.Contains(searchString));
                    return View(await types.ToListAsync());
                }
                else if (toDate != default(DateTime) && fromDate != default(DateTime))
                {
                    //Filters database for products between date range
                    var type = _context.Products.Where(x => x.Farmer_ID == FarmerLogin && x.Product_Date >= fromDate && x.Product_Date <= toDate);
                    return View(await type.ToListAsync());
                }
                else
                {
                   //Displays list of user specific products
                    var AgriEnergyConnectContext = _context.Products.Where(x => x.Farmer_ID == FarmerLogin);
                    return View(await AgriEnergyConnectContext.ToListAsync());
                }

            }


        // GET: Products/Details/5
        // Action method to display details of a specific product
        public async Task<IActionResult> Details(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Farmer)
                .FirstOrDefaultAsync(m => m.Product_ID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // GET: Products/Create
        // Action method to create a new product

        public IActionResult Create()
        {
           // ViewData["Farmer_ID"] = new SelectList(_context.Farmers, "Farmer_ID", "Farmer_ID");
            return View();
        }

        // POST: Products/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Create([Bind("Product_ID,Product_Name,Product_Price,Product_Quantity,Product_Type,Product_Date,Farmer_ID")] Product product)
        {
            if (ModelState.IsValid)
            {
                product.Farmer_ID = HttpContext.Session.GetString("CurrentUser");
                _context.Add(@product);
                await _context.SaveChangesAsync();
                return RedirectToAction(nameof(Index));
            }
            //ViewData["Farmer_ID"] = new SelectList(_context.Farmers, "Farmer_ID", "Farmer_ID", product.Farmer_ID);
            return View(product);
        }

        // GET: Products/Edit/5
        public async Task<IActionResult> Edit(int? id,String FarmerLogin)
        {
           
            FarmerLogin = HttpContext.Session.GetString("CurrentUser");
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products.FindAsync(id);
            if (product == null)
            {
                return NotFound();
            }
            product.Farmer_ID = FarmerLogin;
           // ViewData["Farmer_ID"] = new SelectList(_context.Farmers, "Farmer_ID", "Farmer_ID", product.Farmer_ID);
            return View(product);
        }

        // POST: Products/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to.
        // For more details, see http://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> Edit(int id, [Bind("Product_ID,Product_Name,Product_Price,Product_Quantity,Product_Type,Product_Date,Farmer_ID")] Product product)
        {
           String FarmerLogin = HttpContext.Session.GetString("CurrentUser");
            product.Farmer_ID = FarmerLogin;
            if (id != product.Product_ID)
            {
                return NotFound();
            }

            if (ModelState.IsValid)
            {
                try
                {
                    _context.Update(product);
                    await _context.SaveChangesAsync();
                }
                catch (DbUpdateConcurrencyException)
                {
                    if (!ProductExists(product.Product_ID))
                    {
                        return NotFound();
                    }
                    else
                    {
                        throw;
                    }
                }
                return RedirectToAction(nameof(Index));
            }
           // ViewData["Farmer_ID"] = new SelectList(_context.Farmers, "Farmer_ID", "Farmer_ID", product.Farmer_ID);
            return View(product);
        }

        // GET: Products/Delete/5
        // Retrieving the product to be deleted

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return NotFound();
            }

            var product = await _context.Products
                .Include(p => p.Farmer)
                .FirstOrDefaultAsync(m => m.Product_ID == id);
            if (product == null)
            {
                return NotFound();
            }

            return View(product);
        }

        // Action method to delete a product
        // POST: Products/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public async Task<IActionResult> DeleteConfirmed(int id)
        // Confirming and deleting the specified product

        {
            var product = await _context.Products.FindAsync(id);
            _context.Products.Remove(product);
            await _context.SaveChangesAsync();
            return RedirectToAction(nameof(Index));
        }
        // Method to check if a product exists
        private bool ProductExists(int id)
        {
            return _context.Products.Any(e => e.Product_ID == id);
        }

      
    }
    
}

Agri_Energy_Connect_PROG7311_POE/Views/Farmers/Create.cshtml
@model AgriEnergyConnectApp.Models.Product

@{
    ViewData["Title"] = "Create";
}

<h1>Create</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Create">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Product_Name" class="control-label">Product Name</label>
                <input asp-for="Product_Name" class="form-control" />
                <span asp-validation-for="Product_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Price" class="control-label"></label>
                <input asp-for="Product_Price" class="form-control" />
                <span asp-validation-for="Product_Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Quantity" class="control-label"></label>
                <input asp-for="Product_Quantity" class="form-control" />
                <span asp-validation-for="Product_Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Type" class="control-label"></label>
                <input asp-for="Product_Type" class="form-control" />
                <span asp-validation-for="Product_Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Date" class="control-label"></label>
                <input asp-for="Product_Date" class="form-control" />
                <span asp-validation-for="Product_Date" class="text-danger"></span>
            </div>
          
            <div class="form-group">
                <input type="submit" value="Create" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Agri_Energy_Connect_PROG7311_POE/Views/Farmers/Edit.cshtml
@model AgriEnergyConnectApp.Models.Product

@{
    ViewData["Title"] = "Edit";
}

<h1>Edit</h1>

<h4>Product</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Edit">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Product_ID" />
            <div class="form-group">
                <label asp-for="Product_Name" class="control-label">Product Name</label>
                <input asp-for="Product_Name" class="form-control" />
                <span asp-validation-for="Product_Name" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Price" class="control-label">Product Price</label>
                <input asp-for="Product_Price" class="form-control" />
                <span asp-validation-for="Product_Price" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Quantity" class="control-label">Product Quantity</label>
                <input asp-for="Product_Quantity" class="form-control" />
                <span asp-validation-for="Product_Quantity" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Type" class="control-label">Product Type</label>
                <input asp-for="Product_Type" class="form-control" />
                <span asp-validation-for="Product_Type" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Product_Date" class="control-label">Date</label>
                <input asp-for="Product_Date" class="form-control" />
                <span asp-validation-for="Product_Date" class="text-danger"></span>
            </div>
            
            <div class="form-group">
                <input type="submit" value="Save" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>

<div>
    <a asp-action="Index">Back to List</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Agri_Energy_Connect_PROG7311_POE/Views/Farmers/Index.cshtml
@model IEnumerable<AgriEnergyConnectApp.Models.Farmer>

@{
    ViewData["Title"] = "Index";
}

<h1>Farmers</h1>

<p>
    <a asp-action="Register">Add New Farmer</a>   <div>

    <a asp-controller="Home" asp-action="Emp">Main Menu</a>
</div>
</p>
<table class="table">
    <thead>
        <tr>
            <th>
               Farmer ID
            </th>
            <th>
               Farmer Name
            </th>
            <th></th>
        </tr>
    </thead>
    <tbody>
@foreach (var item in Model) {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Farmer_ID)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.FarmerName)
            </td>
            <td>
                <a asp-action="Products" asp-route-id="@item.Farmer_ID">View Products</a> 
              
            </td>
        </tr>
}
    </tbody>
</table>

Agri_Energy_Connect_PROG7311_POE/Views/Farmers/Login.cshtml
@model AgriEnergyConnectApp.Models.Farmer

@{
    ViewData["Title"] = "Login";
}


<h1>Login</h1>
<h3 style="color:red;">@ViewBag.Login</h3>

<h3 style="color:green;">@ViewBag.Yay</h3>


<h4>Farmer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Login">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Farmer_ID" class="control-label">Farmer ID</label>
                <input asp-for="Farmer_ID" class="form-control" />
                <span asp-validation-for="Farmer_ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type ="Password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Login" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Agri_Energy_Connect_PROG7311_POE/Views/Farmers/Products.cshtml
@model IEnumerable<AgriEnergyConnectApp.Models.Product>

@{
    ViewData["Title"] = "Index";
}

<h1>Products</h1>
<div>
   
    <a asp-action="Index">Back to Farmers</a>
</div>
<form asp-controller="Farmers" asp-action="Products">
    @*<p>
        <input type="submit" value="Show All Products" />
    </p>*@


</form>

<form asp-controller="Farmers" asp-action="Products">
    <p>
        <input type="submit" value="Show all products" />   |  Product Type: <input type="text" name="SearchString" />
        <input type="submit" value="Filter" />   |           Date Range: <input type="date" name="fromDate" />
        <input type="date" name="toDate" />
        <input type="submit" value="Filter" />
    </p>


</form>

<table class="table">
    <thead>
        <tr>
            <th>
                Product Name
            </th>
            <th>
                Product Price
            </th>
            <th>
                Product Quantity
            </th>
            <th>
                Product Type
            </th>
            <th>
                Date
            </th>

            <th></th>
        </tr>
    </thead>
    <tbody>
        @foreach (var item in Model)
        {
            <tr>
                <td>
                    @Html.DisplayFor(modelItem => item.Product_Name)
                </td>
                <td>
                    R   @Html.DisplayFor(modelItem => item.Product_Price) . 00
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product_Quantity)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product_Type)
                </td>
                <td>
                    @Html.DisplayFor(modelItem => item.Product_Date)
                </td>

                <td>
                   
                    <a  asp-action="Edit" asp-route-id="@item.Product_ID">Update</a>

                </td>
            </tr>
        }
    </tbody>

</table>

Agri_Energy_Connect_PROG7311_POE/Views/Farmers/Register.cshtml
@model AgriEnergyConnectApp.Models.Farmer

@{
    ViewData["Title"] = "Register";
}

<h1>Register</h1>

<h4 style="color:red;">@ViewBag.Fail</h4>

<h4>Farmer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Register">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <div class="form-group">
                <label asp-for="Farmer_ID" class="control-label">Farmer ID</label>
                <input asp-for="Farmer_ID" class="form-control" />
                <span asp-validation-for="Farmer_ID" class="text-danger"></span>
            </div>
            <div class="form-group">
                <label asp-for="FarmerName" class="control-label">Farmer Name</label>
                <input asp-for="FarmerName" class="form-control" />
                <span asp-validation-for="FarmerName" class="text-danger"></span>
            </div>

            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div class="form-group">
                <input type="submit" value="Register" class="btn btn-primary" />
            </div>
        </form>
    </div>
</div>



@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}

Agri_Energy_Connect_PROG7311_POE/Views/Farmers/Reset.cshtml
@model AgriEnergyConnectApp.Models.Farmer

@{
    ViewData["Title"] = "Reset";
}

<h1>Update Password</h1>

<h4>Farmer</h4>
<hr />
<div class="row">
    <div class="col-md-4">
        <form asp-action="Reset">
            <div asp-validation-summary="ModelOnly" class="text-danger"></div>
            <input type="hidden" asp-for="Farmer_ID" />
            <div class="form-group">
                @*<label asp-for="FarmerName" class="control-label"></label>*@
                @*<input asp-for="FarmerName" class="form-control" />*@
                <input type="hidden" asp-for="FarmerName" />
                @*<span asp-validation-for="FarmerName" class="text-danger"></span>*@
            </div>
            <div class="form-group">
                <label asp-for="Password" class="control-label"></label>
                <input asp-for="Password" class="form-control" type ="Password" />
                <span asp-validation-for="Password" class="text-danger"></span>
            </div>
            <div> <input type="submit" value="Save" class="btn btn-primary" /></div>
            @*<div class="form-group">
                <a asp-controller="Home" asp-action="New"></a>  <input type="submit" value="Save" class="btn btn-primary" />
            </div>*@
        </form>
        @*<form  asp-controller="Home" asp-action="New" >
            <input type="submit" value="Save" class="btn btn-primary" />
        </form>*@
    </div>
</div>

<div>
    <a asp-controller="Home" asp-action="New">Back to Main menu</a>
</div>

@section Scripts {
    @{await Html.RenderPartialAsync("_ValidationScriptsPartial");}
}